# Generated by Django 4.1.7 on 2023-03-22 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregister',
            name='profile_photo',
            field=models.ImageField(default=1, upload_to='uploads/% Y/% m/% d/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentregister',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.student'),
        ),
    ]
