# Generated by Django 4.1.7 on 2023-03-24 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentregister_profile_photo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentRegister',
        ),
    ]
