# Generated by Django 4.1.7 on 2023-04-01 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_course_studentdetials_purchase'),
        ('students', '0003_delete_studentregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegister',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.student')),
                ('profile_photo', models.ImageField(upload_to='uploads/% Y/% m/% d/')),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=225)),
            ],
        ),
    ]
