# Generated by Django 4.1.7 on 2023-04-30 18:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_email_user_phone_number_teacherdetials_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.course'),
        ),
        migrations.DeleteModel(
            name='Teacher_Course_Select',
        ),
    ]
