# Generated by Django 4.1.7 on 2023-03-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.IntegerField(default=22),
            preserve_default=False,
        ),
    ]
