# Generated by Django 4.1.7 on 2023-04-20 19:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_teacher_course_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_course_select',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
