# Generated by Django 4.1.7 on 2023-04-25 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_teacher_course_select_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.teacher_course_select'),
        ),
    ]
